# Generated by Django 5.1.7 on 2025-03-24 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_hospital_display_alter_bloodbank_units_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospital',
            name='display',
            field=models.ImageField(blank=True, null=True, upload_to='hospital_images/'),
        ),
    ]
