# Generated by Django 5.1.7 on 2025-03-24 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_hospital_display'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospital',
            name='display',
            field=models.FileField(blank=True, null=True, upload_to='hospital_images/'),
        ),
    ]
