# Generated by Django 5.1.7 on 2025-05-29 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_department_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='cabin_beds',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='hospital',
            name='general_beds',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='hospital',
            name='icu_beds',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='hospital',
            name='ventilator_beds',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
