# Generated by Django 5.1.7 on 2025-05-31 14:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_hospital_cabin_beds_hospital_general_beds_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='hospital',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.hospital'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='name',
            field=models.CharField(default='Unnamed Doctor', max_length=100),
        ),
        migrations.AddField(
            model_name='doctor',
            name='qualification',
            field=models.CharField(default='unknonwed', max_length=100),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='slot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.slot'),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='display',
            field=models.FileField(blank=True, null=True, upload_to='media/hospital_images/'),
        ),
    ]
