# Generated by Django 5.1.7 on 2025-05-31 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_appointment_date_doctor_hospital_doctor_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='user',
        ),
    ]
